"""Pure Markdown renderers for the deployment support bundle."""

from typing import Any


def support_bundle_readme(report: dict[str, Any]) -> str:
    delivery = _dict_or_empty(report.get("delivery"))
    diagnostics = _dict_or_empty(report.get("diagnostics"))
    info = _dict_or_empty(diagnostics.get("info"))
    return "\n".join(
        [
            "# AgentHive Deployment Support Bundle",
            "",
            "This package is generated by AgentHive for private deployment acceptance, implementation support, and customer IT review.",
            "",
            "## Contents",
            "",
            "- `diagnostics.json`: redacted machine-readable health, readiness, delivery, and deployment identity evidence.",
            "- `acceptance-checklist.md`: customer-facing sign-off checklist with delivery gate evidence.",
            "- `delivery-summary.md`: human-readable delivery status, blockers, warnings, and remediation notes.",
            "- `manifest.json`: bundle metadata for support intake and archive tracking.",
            "",
            "## Snapshot",
            "",
            f"- Product: {info.get('name', 'AgentHive')} {info.get('version', '-')}",
            f"- Edition: {info.get('edition', '-')}",
            f"- Generated at: {report.get('generated_at', '-')}",
            f"- Delivery status: {delivery.get('status', '-')}",
            f"- Blockers: {delivery.get('blocker_count', '-')}",
            f"- Warnings: {delivery.get('warning_count', '-')}",
            "",
            "All sensitive fields are redacted before packaging. Do not manually add API keys, passwords, tokens, or private license material to this bundle.",
            "",
        ]
    )


def support_bundle_acceptance_checklist(report: dict[str, Any]) -> str:
    diagnostics = _dict_or_empty(report.get("diagnostics"))
    readiness = _dict_or_empty(diagnostics.get("readiness"))
    health = _dict_or_empty(diagnostics.get("health"))
    info = _dict_or_empty(diagnostics.get("info"))
    connection_acceptance = _dict_or_empty(diagnostics.get("connection_acceptance"))
    knowledge_acceptance = _dict_or_empty(diagnostics.get("knowledge_acceptance"))
    delivery = _dict_or_empty(report.get("delivery"))
    components = _dict_or_empty(readiness.get("components"))
    identity = _dict_or_empty(
        components.get("license_identity")
        or _dict_or_empty(health.get("components")).get("license_identity")
    )
    production_config = _dict_or_empty(
        components.get("production_config")
        or _dict_or_empty(health.get("components")).get("production_config")
    )
    decision = acceptance_decision(delivery)
    lines = [
        "# AgentHive Acceptance Checklist",
        "",
        "This checklist is generated from the redacted AgentHive diagnostics package for customer sign-off.",
        "",
        "## Decision",
        "",
        f"- Product: {info.get('name', 'AgentHive')} {info.get('version', '-')}",
        f"- Edition: {info.get('edition', '-')}",
        f"- Generated at: {report.get('generated_at', '-')}",
        f"- Readiness status: {readiness.get('status', '-')}",
        f"- Delivery status: {delivery.get('status', '-')}",
        f"- Acceptance decision: {decision}",
        f"- Blockers: {delivery.get('blocker_count', '-')}",
        f"- Warnings: {delivery.get('warning_count', '-')}",
        "",
        "## Required Evidence",
        "",
        *[
            acceptance_evidence_line(component_id, label, components)
            for component_id, label in [
                ("database", "PostgreSQL business database"),
                ("redis", "Redis cache and queue runtime"),
                ("minio", "MinIO object storage"),
                ("pgvector", "PostgreSQL pgvector retrieval store"),
                ("litellm", "LiteLLM model gateway"),
                ("license_identity", "License install identity"),
                ("production_config", "Production secret/config gate"),
                ("agent_runtime", "LangChain/LangGraph Agent runtime"),
                ("media_generation", "Media generation gateway"),
                ("media_worker", "Media generation worker queue"),
                ("frontend", "AgentHive management console"),
            ]
        ],
        "",
        "## Deployment Identity",
        "",
        *acceptance_component_detail_lines(identity),
        "",
        "## Production Configuration",
        "",
        *acceptance_component_detail_lines(production_config),
        "",
        "## Model and Media Connection Evidence",
        "",
        *connection_acceptance_lines(connection_acceptance),
        "",
        "## Knowledge Agent Evidence",
        "",
        *knowledge_acceptance_lines(knowledge_acceptance),
        "",
        "## Open Blockers",
        "",
        *support_bundle_issue_lines(delivery.get("blockers")),
        "",
        "## Open Warnings",
        "",
        *support_bundle_issue_lines(delivery.get("warnings")),
        "",
        "## Sign-off",
        "",
        "- Customer organization:",
        "- Customer owner:",
        "- Implementer:",
        "- Acceptance date:",
        "- Notes:",
        "",
        "## Post-Handoff Actions",
        "",
        "1. Archive this support bundle with the customer contract and License record.",
        "2. Confirm backup and restore ownership with customer IT.",
        "3. Record enabled Agent modules, model providers, and cost-center owners.",
        "4. Keep API keys, passwords, private keys, and raw License material outside this bundle.",
        "",
    ]
    return "\n".join(lines)


def support_bundle_delivery_summary(report: dict[str, Any]) -> str:
    diagnostics = _dict_or_empty(report.get("diagnostics"))
    readiness = _dict_or_empty(diagnostics.get("readiness"))
    connection_acceptance = _dict_or_empty(diagnostics.get("connection_acceptance"))
    knowledge_acceptance = _dict_or_empty(diagnostics.get("knowledge_acceptance"))
    delivery = _dict_or_empty(report.get("delivery"))
    components = _dict_or_empty(readiness.get("components"))
    lines = [
        "# AgentHive Delivery Summary",
        "",
        f"- Generated at: {report.get('generated_at', '-')}",
        f"- Readiness status: {readiness.get('status', '-')}",
        f"- Delivery status: {delivery.get('status', '-')}",
        f"- Summary: {delivery.get('summary', '-')}",
        f"- Blockers: {delivery.get('blocker_count', '-')}",
        f"- Warnings: {delivery.get('warning_count', '-')}",
        "",
        "## Blockers",
        "",
        *support_bundle_issue_lines(delivery.get("blockers")),
        "",
        "## Warnings",
        "",
        *support_bundle_issue_lines(delivery.get("warnings")),
        "",
        "## Model and Media Connection Evidence",
        "",
        *connection_acceptance_lines(connection_acceptance),
        "",
        "## Knowledge Agent Evidence",
        "",
        *knowledge_acceptance_lines(knowledge_acceptance),
        "",
        "## Component Evidence",
        "",
        "| Component | Status | Message |",
        "| --- | --- | --- |",
    ]
    for name, component in sorted(components.items()):
        component_report = _dict_or_empty(component)
        lines.append(
            f"| {name} | {component_report.get('status', '-')} | {_markdown_cell(str(component_report.get('message', '-')))} |"
        )
    lines.append("")
    return "\n".join(lines)


def acceptance_decision(delivery: dict[str, Any]) -> str:
    status_value = str(delivery.get("status", "unknown"))
    if status_value == "ready":
        return "pass"
    if status_value == "ready_with_warnings":
        return "conditional_pass"
    if status_value == "blocked":
        return "blocked"
    return "manual_review"


def acceptance_evidence_line(component_id: str, label: str, components: dict[str, Any]) -> str:
    component = _dict_or_empty(components.get(component_id))
    status_value = str(component.get("status", "missing"))
    marker = "[x]" if status_value == "healthy" else "[ ]"
    message = _markdown_cell(str(component.get("message", "not reported")))
    return f"- {marker} **{label}** (`{component_id}`): {status_value} - {message}"


def acceptance_component_detail_lines(component: dict[str, Any]) -> list[str]:
    if not component:
        return ["- status: not_reported"]
    lines = [
        f"- status: {component.get('status', '-')}",
        f"- message: {component.get('message', '-')}",
    ]
    details = _dict_or_empty(component.get("details"))
    for key, value in sorted(details.items()):
        lines.append(f"- {key}: {_markdown_cell(str(value))}")
    return lines


def connection_acceptance_lines(evidence: dict[str, Any]) -> list[str]:
    if not evidence:
        return [
            "- status: not_reported",
            "- summary: No connection acceptance evidence was attached.",
        ]
    lines = [
        f"- status: {evidence.get('status', '-')}",
        f"- summary: {_markdown_cell(str(evidence.get('summary', '-')))}",
        f"- recent tests: {evidence.get('recent_test_count', 0)}",
        f"- live network calls: {evidence.get('live_network_call_count', 0)}",
        f"- media live probes: {evidence.get('media_live_probe_count', 0)}",
        f"- recent failures: {evidence.get('failed_recent_count', 0)}",
        f"- providers: {_markdown_cell(', '.join(evidence.get('providers', [])) or '-')}",
    ]
    latest_live_probe = _dict_or_empty(evidence.get("latest_live_probe"))
    latest_media_live_probe = _dict_or_empty(evidence.get("latest_media_live_probe"))
    if latest_live_probe:
        lines.extend(["", "Latest live provider probe:", *connection_probe_detail_lines(latest_live_probe)])
    if latest_media_live_probe and latest_media_live_probe != latest_live_probe:
        lines.extend(
            [
                "",
                "Latest media provider live probe:",
                *connection_probe_detail_lines(latest_media_live_probe),
            ]
        )
    return lines


def connection_probe_detail_lines(item: dict[str, Any]) -> list[str]:
    return [
        f"- provider: {item.get('provider_key', '-')}",
        f"- model: {item.get('model_key', '-')}",
        f"- operation: {item.get('operation', '-')}",
        f"- ok: {item.get('ok', '-')}",
        f"- checked_at: {item.get('checked_at', '-')}",
        f"- HTTP status: {item.get('status_code', '-')}",
        f"- probe path: {item.get('probe_path', '-')}",
        f"- latency_ms: {item.get('latency_ms', '-')}",
    ]


def knowledge_acceptance_lines(evidence: dict[str, Any]) -> list[str]:
    if not evidence:
        return ["- status: not_reported", "- summary: No knowledge Agent evidence was attached."]
    lines = [
        f"- status: {evidence.get('status', '-')}",
        f"- summary: {_markdown_cell(str(evidence.get('summary', '-')))}",
        f"- recent runs: {evidence.get('recent_run_count', 0)}",
        f"- knowledge-enabled runs: {evidence.get('knowledge_enabled_run_count', 0)}",
        f"- runs with sources: {evidence.get('runs_with_sources_count', 0)}",
        f"- human review required: {evidence.get('human_review_required_count', 0)}",
        f"- guardrail triggered: {evidence.get('guardrail_triggered_count', 0)}",
        f"- agents: {_markdown_cell(', '.join(evidence.get('agents', [])) or '-')}",
    ]
    latest_run = _dict_or_empty(evidence.get("latest_knowledge_run"))
    if latest_run:
        lines.extend(["", "Latest knowledge-backed Agent run:", *knowledge_run_detail_lines(latest_run)])
    return lines


def knowledge_run_detail_lines(item: dict[str, Any]) -> list[str]:
    return [
        f"- agent: {item.get('agent_key', '-')}",
        f"- instance: {item.get('agent_instance_name') or item.get('agent_instance_id') or '-'}",
        f"- model: {item.get('model_key', '-')}",
        f"- checked_at: {item.get('checked_at', '-')}",
        f"- sources: {item.get('source_count', '-')}",
        f"- confidence: {item.get('confidence_level', '-')}",
        f"- max_score: {item.get('max_score', '-')}",
        f"- review_required: {item.get('requires_human_review', '-')}",
        f"- guardrail: {item.get('guardrail_mode', '-')}",
    ]


def support_bundle_issue_lines(value: Any) -> list[str]:
    if not isinstance(value, list) or not value:
        return ["No issues reported."]
    lines: list[str] = []
    for item in value:
        check = _dict_or_empty(item)
        remediation = _dict_or_empty(check.get("remediation"))
        lines.extend(
            [
                f"- **{check.get('label', check.get('id', 'unknown'))}**",
                f"  - Component: {check.get('component', '-')}",
                f"  - Status: {check.get('status', '-')}",
                f"  - Message: {check.get('message', '-')}",
            ]
        )
        if remediation:
            lines.append(
                f"  - Remediation: {remediation.get('summary', '')} {remediation.get('action', '')}".strip()
            )
    return lines


def _markdown_cell(value: str) -> str:
    return value.replace("|", "\\|").replace("\n", " ")


def _dict_or_empty(value: Any) -> dict[str, Any]:
    return value if isinstance(value, dict) else {}
