import type {
  LLMConnectionTestHistoryItem,
  LLMConnectionTestRequest,
  LLMConnectionTestResponse,
  LLMCredentialResponse,
  LLMDeploymentAcceptanceTestResponse,
  LLMDeploymentResponse,
  LLMModelPriceResponse,
  LLMModelPriceUpsertRequest,
  LLMPolicyResponse,
  LLMPolicyStatus,
  LLMPolicyUpsertRequest,
  LLMProviderResponse,
  LLMReadinessResponse,
} from "../../lib/api";

const PROTOTYPE_NOW = "2026-01-01T00:00:00.000Z";
const PROTOTYPE_TENANT_ID = "00000000-0000-4000-8000-000000000001";

export const PROTOTYPE_MODEL_PROVIDERS: LLMProviderResponse[] = [
  {
    adapter_type: "litellm",
    base_url: null,
    capabilities: ["chat", "vision", "tool_calling", "json_mode"],
    credential_configured: true,
    metadata: { governance: "tenant-default", regions: ["us", "eu"] },
    name: "OpenAI GPT",
    provider_key: "openai",
    region: "global",
    status: "active",
  },
  {
    adapter_type: "litellm",
    base_url: null,
    capabilities: ["chat", "long_context", "tool_calling"],
    credential_configured: true,
    metadata: { governance: "department-key", regions: ["us"] },
    name: "Anthropic Claude",
    provider_key: "anthropic",
    region: "global",
    status: "active",
  },
  {
    adapter_type: "anthropic_compatible",
    base_url: "",
    capabilities: ["chat", "stream", "long_context"],
    credential_configured: false,
    metadata: { governance: "private-endpoint", protocol: "anthropic-compatible" },
    name: "Anthropic-compatible Endpoint",
    provider_key: "anthropic_compatible",
    region: "private",
    status: "not_configured",
  },
  {
    adapter_type: "litellm",
    base_url: null,
    capabilities: ["chat", "vision", "long_context"],
    credential_configured: true,
    metadata: { governance: "tenant-default", regions: ["global"] },
    name: "Google Gemini",
    provider_key: "gemini",
    region: "global",
    status: "active",
  },
  {
    adapter_type: "openai_compatible",
    base_url: "https://dashscope.aliyuncs.com/compatible-mode/v1",
    capabilities: ["chat", "embedding", "tool_calling"],
    credential_configured: true,
    metadata: { governance: "china-primary", owner: "customer-success" },
    name: "Qwen",
    provider_key: "qwen",
    region: "cn",
    status: "active",
  },
  {
    adapter_type: "openai_compatible",
    base_url: "https://api.deepseek.com",
    capabilities: ["chat", "reasoning", "coding"],
    credential_configured: true,
    metadata: { governance: "cost-optimized", fallback_for: ["openai", "qwen"] },
    name: "DeepSeek",
    provider_key: "deepseek",
    region: "cn",
    status: "active",
  },
  {
    adapter_type: "openai_compatible",
    base_url: "https://api.moonshot.cn/v1",
    capabilities: ["chat", "long_context"],
    credential_configured: true,
    metadata: { governance: "long-context", max_context: 128000 },
    name: "Kimi",
    provider_key: "kimi",
    region: "cn",
    status: "active",
  },
  {
    adapter_type: "openai_compatible",
    base_url: "https://api.minimax.chat/v1",
    capabilities: ["chat", "voice", "multimodal"],
    credential_configured: false,
    metadata: { governance: "optional-module" },
    name: "MiniMax",
    provider_key: "minimax",
    region: "cn",
    status: "not_configured",
  },
  {
    adapter_type: "openai_compatible",
    base_url: "",
    capabilities: ["chat", "reasoning"],
    credential_configured: false,
    metadata: { governance: "optional-module", protocol: "openai-compatible" },
    name: "MiMo",
    provider_key: "mimo",
    region: "cn",
    status: "not_configured",
  },
  {
    adapter_type: "openai_compatible",
    base_url: "https://open.bigmodel.cn/api/paas/v4",
    capabilities: ["chat", "tool_calling"],
    credential_configured: false,
    metadata: { governance: "optional-module" },
    name: "GLM",
    provider_key: "glm",
    region: "cn",
    status: "not_configured",
  },
  {
    adapter_type: "litellm",
    base_url: "http://litellm:4000",
    capabilities: ["routing", "fallback", "virtual_key", "budget"],
    credential_configured: true,
    metadata: { control_plane: "protocol-adapter" },
    name: "LiteLLM Proxy",
    provider_key: "litellm",
    region: "private",
    status: "active",
  },
  {
    adapter_type: "openai_compatible",
    base_url: "https://llm-gateway.customer.example/v1",
    capabilities: ["chat", "embedding", "private_endpoint"],
    credential_configured: true,
    metadata: { governance: "bring-your-own-endpoint" },
    name: "OpenAI-compatible",
    provider_key: "openai_compatible",
    region: "private",
    status: "active",
  },
  {
    adapter_type: "openai_compatible",
    base_url: "http://ollama:11434/v1",
    capabilities: ["chat", "local", "offline"],
    credential_configured: true,
    metadata: { governance: "offline-fallback" },
    name: "Ollama",
    provider_key: "ollama",
    region: "local",
    status: "active",
  },
  {
    adapter_type: "openai_compatible",
    base_url: "https://api.openai.com/v1",
    capabilities: ["image_generation", "reference_image"],
    credential_configured: false,
    metadata: { governance: "optional-media-module", probe_path: "/models" },
    name: "OpenAI Images",
    provider_key: "openai_images",
    region: "global",
    status: "not_configured",
  },
  {
    adapter_type: "openai_compatible",
    base_url: "https://media-gateway.customer.example/v1",
    capabilities: ["image_generation", "reference_image", "style_transfer"],
    credential_configured: false,
    metadata: { governance: "optional-media-module", probe_path: "/models" },
    name: "Nano Banana",
    provider_key: "nano_banana",
    region: "global",
    status: "not_configured",
  },
  {
    adapter_type: "openai_compatible",
    base_url: "https://ark.cn-beijing.volces.com/api/v3",
    capabilities: ["video_generation", "reference_image_to_video", "reference_video", "async_job"],
    credential_configured: false,
    metadata: { governance: "optional-media-module", probe_path: "/models" },
    name: "Volcengine Seedance",
    provider_key: "volcengine_seedance",
    region: "cn",
    status: "not_configured",
  },
  {
    adapter_type: "openai_compatible",
    base_url: "https://private-media.customer.example/v1",
    capabilities: ["image_generation", "video_generation", "private_endpoint"],
    credential_configured: false,
    metadata: { governance: "bring-your-own-media-endpoint", probe_path: "/models" },
    name: "Private OpenAI-compatible Media",
    provider_key: "openai_compatible_media",
    region: "private",
    status: "not_configured",
  },
];

export const PROTOTYPE_MODEL_DEPLOYMENTS: LLMDeploymentResponse[] = [
  {
    adapter_type: "litellm",
    capabilities: ["chat", "vision", "tool_calling"],
    config: { fallback: ["deepseek-v4-flash", "qwen-plus"], policy: "premium-quality" },
    context_window: 128000,
    deployment_name: "Global Premium Chat",
    display_name: "GPT-4o",
    id: "00000000-0000-4000-8000-000000100001",
    model_key: "gpt-4o",
    priority: 10,
    provider_key: "openai",
    provider_name: "OpenAI GPT",
    routing_key: "premium-chat",
    status: "active",
  },
  {
    adapter_type: "litellm",
    capabilities: ["chat", "long_context", "tool_calling"],
    config: { fallback: ["gpt-4o-mini"], policy: "high-accuracy" },
    context_window: 200000,
    deployment_name: "Executive Analysis",
    display_name: "Claude Sonnet",
    id: "00000000-0000-4000-8000-000000100002",
    model_key: "claude-3-5-sonnet",
    priority: 20,
    provider_key: "anthropic",
    provider_name: "Anthropic Claude",
    routing_key: "analysis-chat",
    status: "active",
  },
  {
    adapter_type: "anthropic_compatible",
    capabilities: ["chat", "stream", "long_context"],
    config: { protocol: "anthropic-compatible", requires_configuration: true },
    context_window: 200000,
    deployment_name: "Private Claude-compatible Chat",
    display_name: "Claude-compatible",
    id: "00000000-0000-4000-8000-000000100012",
    model_key: "claude-compatible",
    priority: 120,
    provider_key: "anthropic_compatible",
    provider_name: "Anthropic-compatible Endpoint",
    routing_key: "anthropic-private-chat",
    status: "inactive",
  },
  {
    adapter_type: "litellm",
    capabilities: ["chat", "vision", "long_context"],
    config: { policy: "multimodal-review" },
    context_window: 1000000,
    deployment_name: "Multimodal Review",
    display_name: "Gemini Pro",
    id: "00000000-0000-4000-8000-000000100003",
    model_key: "gemini-1.5-pro",
    priority: 30,
    provider_key: "gemini",
    provider_name: "Google Gemini",
    routing_key: "vision-chat",
    status: "active",
  },
  {
    adapter_type: "openai_compatible",
    capabilities: ["chat", "embedding", "tool_calling"],
    config: { policy: "china-primary", budget_scope: "department" },
    context_window: 131000,
    deployment_name: "China Primary Chat",
    display_name: "Qwen Plus",
    id: "00000000-0000-4000-8000-000000100004",
    model_key: "qwen-plus",
    priority: 5,
    provider_key: "qwen",
    provider_name: "Qwen",
    routing_key: "cn-primary-chat",
    status: "active",
  },
  {
    adapter_type: "openai_compatible",
    capabilities: ["chat", "reasoning", "coding"],
    config: { policy: "cost-optimized", fallback_for: ["premium-chat", "cn-primary-chat"] },
    context_window: 64000,
    deployment_name: "Cost Optimized Reasoning",
    display_name: "DeepSeek V4 Flash",
    id: "00000000-0000-4000-8000-000000100005",
    model_key: "deepseek-v4-flash",
    priority: 6,
    provider_key: "deepseek",
    provider_name: "DeepSeek",
    routing_key: "cost-chat",
    status: "active",
  },
  {
    adapter_type: "openai_compatible",
    capabilities: ["chat", "long_context"],
    config: { policy: "document-heavy" },
    context_window: 128000,
    deployment_name: "Long Context Documents",
    display_name: "Kimi 128K",
    id: "00000000-0000-4000-8000-000000100006",
    model_key: "moonshot-v1-128k",
    priority: 40,
    provider_key: "kimi",
    provider_name: "Kimi",
    routing_key: "long-context-chat",
    status: "active",
  },
  {
    adapter_type: "openai_compatible",
    capabilities: ["chat", "reasoning"],
    config: { policy: "optional-china-reasoning", requires_configuration: true },
    context_window: 32768,
    deployment_name: "Mimo Optional Reasoning",
    display_name: "MiMo Chat",
    id: "00000000-0000-4000-8000-000000100008",
    model_key: "mimo-chat",
    priority: 45,
    provider_key: "mimo",
    provider_name: "MiMo",
    routing_key: "mimo-chat",
    status: "inactive",
  },
  {
    adapter_type: "openai_compatible",
    capabilities: ["chat", "local", "offline"],
    config: { policy: "offline-demo", live_network_call: false },
    context_window: 32000,
    deployment_name: "Offline Local Fallback",
    display_name: "Llama 3.1 Local",
    id: "00000000-0000-4000-8000-000000100007",
    model_key: "llama3.1",
    priority: 100,
    provider_key: "ollama",
    provider_name: "Ollama",
    routing_key: "offline-chat",
    status: "active",
  },
];

export const PROTOTYPE_MODEL_POLICIES: LLMPolicyResponse[] = [
  {
    allowed_models: ["qwen-plus", "deepseek-v4-flash", "mimo-chat", "gpt-4o-mini"],
    allowed_routing_keys: ["cn-primary-chat", "cost-chat", "mimo-chat", "default-chat"],
    created_at: PROTOTYPE_NOW,
    default_model_key: "qwen-plus",
    default_routing_key: "cn-primary-chat",
    description: "Tenant default route keeps China-friendly models primary and falls back through LiteLLM.",
    effect: "allow",
    id: "00000000-0000-4000-8000-000000110001",
    max_tokens: 4096,
    metadata: { budget_scope: "tenant", deny_overrides_allowed: true },
    name: "Tenant default model policy",
    priority: 100,
    scope_id: null,
    scope_type: "tenant",
    status: "active",
    tenant_id: PROTOTYPE_TENANT_ID,
    updated_at: PROTOTYPE_NOW,
  },
  {
    allowed_models: ["qwen-plus", "deepseek-v4-flash", "mimo-chat", "moonshot-v1-128k"],
    allowed_routing_keys: ["cn-primary-chat", "cost-chat", "mimo-chat", "long-context-chat"],
    created_at: PROTOTYPE_NOW,
    default_model_key: "qwen-plus",
    default_routing_key: "cn-primary-chat",
    description: "Customer Success can use long-context document answers within a department budget.",
    effect: "allow",
    id: "00000000-0000-4000-8000-000000110002",
    max_tokens: 8192,
    metadata: { department: "Customer Success", monthly_budget_usd: 2500 },
    name: "Customer Success department policy",
    priority: 90,
    scope_id: "00000000-0000-4000-8000-000000000301",
    scope_type: "department",
    status: "active",
    tenant_id: PROTOTYPE_TENANT_ID,
    updated_at: PROTOTYPE_NOW,
  },
  {
    allowed_models: ["gpt-4o", "claude-3-5-sonnet"],
    allowed_routing_keys: ["premium-chat", "analysis-chat"],
    created_at: PROTOTYPE_NOW,
    default_model_key: null,
    default_routing_key: null,
    description: "Copywriting agent cannot use premium routes unless explicitly approved.",
    effect: "deny",
    id: "00000000-0000-4000-8000-000000110003",
    max_tokens: 2048,
    metadata: { reason: "cost-control", fallback: "cost-chat" },
    name: "Deny premium routes for copywriting",
    priority: 10,
    scope_id: "00000000-0000-4000-8000-000000000701",
    scope_type: "agent",
    status: "active",
    tenant_id: PROTOTYPE_TENANT_ID,
    updated_at: PROTOTYPE_NOW,
  },
];

export const PROTOTYPE_MODEL_PRICES: LLMModelPriceResponse[] = [
  {
    currency: "USD",
    display_name: "GPT-4o",
    effective_from: PROTOTYPE_NOW,
    effective_to: null,
    id: "00000000-0000-4000-8000-000000120001",
    input_per_1k_tokens: "0.0050",
    model_id: "00000000-0000-4000-8000-000000100001",
    model_key: "gpt-4o",
    output_per_1k_tokens: "0.0150",
    provider_key: "openai",
  },
  {
    currency: "USD",
    display_name: "Claude Sonnet",
    effective_from: PROTOTYPE_NOW,
    effective_to: null,
    id: "00000000-0000-4000-8000-000000120002",
    input_per_1k_tokens: "0.0030",
    model_id: "00000000-0000-4000-8000-000000100002",
    model_key: "claude-3-5-sonnet",
    output_per_1k_tokens: "0.0150",
    provider_key: "anthropic",
  },
  {
    currency: "CNY",
    display_name: "Qwen Plus",
    effective_from: PROTOTYPE_NOW,
    effective_to: null,
    id: "00000000-0000-4000-8000-000000120003",
    input_per_1k_tokens: "0.0008",
    model_id: "00000000-0000-4000-8000-000000100004",
    model_key: "qwen-plus",
    output_per_1k_tokens: "0.0020",
    provider_key: "qwen",
  },
  {
    currency: "CNY",
    display_name: "DeepSeek V4 Flash",
    effective_from: PROTOTYPE_NOW,
    effective_to: null,
    id: "00000000-0000-4000-8000-000000120004",
    input_per_1k_tokens: "0.0005",
    model_id: "00000000-0000-4000-8000-000000100005",
    model_key: "deepseek-v4-flash",
    output_per_1k_tokens: "0.0015",
    provider_key: "deepseek",
  },
  {
    currency: "CNY",
    display_name: "MiMo Chat",
    effective_from: PROTOTYPE_NOW,
    effective_to: null,
    id: "00000000-0000-4000-8000-000000120005",
    input_per_1k_tokens: "0.0000",
    model_id: "00000000-0000-4000-8000-000000100008",
    model_key: "mimo-chat",
    output_per_1k_tokens: "0.0000",
    provider_key: "mimo",
  },
];

export const PROTOTYPE_MODEL_CONNECTION_TESTS: LLMConnectionTestHistoryItem[] = [
  {
    actor_id: "00000000-0000-4000-8000-000000000201",
    adapter_type: "openai_compatible",
    checked_at: "2026-01-01T09:10:00.000Z",
    deployment_id: "00000000-0000-4000-8000-000000100004",
    fallback_attempt_count: 0,
    id: "00000000-0000-4000-8000-000000130001",
    latency_ms: 186,
    live_network_call: true,
    message: "Qwen route healthy.",
    model_key: "qwen-plus",
    ok: true,
    operation: "model_connection_check",
    provider_key: "qwen",
    provider_type: "openai_compatible",
    configuration_source: "prototype",
    probe_path: null,
    request_id: "req_model_demo_001",
    selected_route_reason: "department policy matched Customer Success",
    status_code: null,
    status: "success",
    temporary_api_key_provided: false,
    temporary_base_url_provided: false,
  },
  {
    actor_id: "00000000-0000-4000-8000-000000000201",
    adapter_type: "openai_compatible",
    checked_at: "2026-01-01T09:02:00.000Z",
    deployment_id: "00000000-0000-4000-8000-000000100008",
    fallback_attempt_count: 0,
    id: "00000000-0000-4000-8000-000000130005",
    latency_ms: 0,
    live_network_call: false,
    message: "MiMo route is available after customer Base URL and API key are configured.",
    model_key: "mimo-chat",
    ok: false,
    operation: "model_connection_check",
    provider_key: "mimo",
    provider_type: "openai_compatible",
    configuration_source: "prototype",
    probe_path: null,
    request_id: "req_model_demo_005",
    selected_route_reason: "optional provider awaiting credential",
    status_code: null,
    status: "not_configured",
    temporary_api_key_provided: false,
    temporary_base_url_provided: false,
  },
  {
    actor_id: "00000000-0000-4000-8000-000000000201",
    adapter_type: "openai_compatible",
    checked_at: "2026-01-01T09:08:00.000Z",
    deployment_id: "00000000-0000-4000-8000-000000100005",
    fallback_attempt_count: 1,
    id: "00000000-0000-4000-8000-000000130002",
    latency_ms: 243,
    live_network_call: true,
    message: "DeepSeek fallback route accepted.",
    model_key: "deepseek-v4-flash",
    ok: true,
    operation: "model_connection_check",
    provider_key: "deepseek",
    provider_type: "openai_compatible",
    configuration_source: "prototype",
    probe_path: null,
    request_id: "req_model_demo_002",
    selected_route_reason: "premium route budget guard selected cost fallback",
    status_code: null,
    status: "success",
    temporary_api_key_provided: false,
    temporary_base_url_provided: false,
  },
  {
    actor_id: "00000000-0000-4000-8000-000000000201",
    adapter_type: "openai_compatible",
    checked_at: "2026-01-01T09:04:00.000Z",
    deployment_id: "00000000-0000-4000-8000-000000100006",
    fallback_attempt_count: 0,
    id: "00000000-0000-4000-8000-000000130003",
    latency_ms: 412,
    live_network_call: true,
    message: "Kimi long context route accepted.",
    model_key: "moonshot-v1-128k",
    ok: true,
    operation: "model_connection_check",
    provider_key: "kimi",
    provider_type: "openai_compatible",
    configuration_source: "prototype",
    probe_path: null,
    request_id: "req_model_demo_003",
    selected_route_reason: "document-heavy workload requested long context",
    status_code: null,
    status: "success",
    temporary_api_key_provided: true,
    temporary_base_url_provided: false,
  },
  {
    actor_id: "00000000-0000-4000-8000-000000000201",
    adapter_type: "openai_compatible",
    checked_at: "2026-01-01T08:58:00.000Z",
    deployment_id: "00000000-0000-4000-8000-000000100007",
    fallback_attempt_count: 0,
    id: "00000000-0000-4000-8000-000000130004",
    latency_ms: 38,
    live_network_call: false,
    message: "Offline local fallback verified with mock adapter.",
    model_key: "llama3.1",
    ok: true,
    operation: "model_connection_check",
    provider_key: "ollama",
    provider_type: "ollama",
    configuration_source: "prototype",
    probe_path: null,
    request_id: "req_model_demo_004",
    selected_route_reason: "private deployment offline health check",
    status_code: null,
    status: "success",
    temporary_api_key_provided: false,
    temporary_base_url_provided: false,
  },
];

export function createPrototypeCredentialResponse(
  providerKey: string,
  payload: {
    base_url?: string | null;
    display_name: string;
    model_key?: string | null;
    owner_id?: string | null;
    owner_type?: string;
    routing_key?: string | null;
  },
): LLMCredentialResponse {
  const secretSuffix = providerKey.slice(0, 3).padEnd(3, "x").toUpperCase();
  return {
    base_url:
      payload.base_url ??
      PROTOTYPE_MODEL_PROVIDERS.find((provider) => provider.provider_key === providerKey)?.base_url ??
      null,
    credential_configured: true,
    deployment_id:
      PROTOTYPE_MODEL_DEPLOYMENTS.find((deployment) => deployment.provider_key === providerKey)?.id ?? null,
    display_name: payload.display_name,
    masked_secret: `sk-...${secretSuffix}`,
    model_key: payload.model_key ?? null,
    owner_id: payload.owner_id ?? null,
    owner_type: payload.owner_type ?? "tenant",
    provider_key: providerKey,
    routing_key: payload.routing_key ?? null,
  };
}

export function createPrototypeConnectionTest(payload: LLMConnectionTestRequest): LLMConnectionTestResponse {
  const providerKey = payload.provider_key ?? "openai_compatible";
  const provider = PROTOTYPE_MODEL_PROVIDERS.find((item) => item.provider_key === providerKey);
  return {
    adapter_type: payload.adapter_type ?? provider?.adapter_type ?? "openai_compatible",
    checked_at: new Date().toISOString(),
    diagnostics: {
      fallback_attempts: 0,
      live_network_call: false,
      mode: "prototype",
      operation: payload.live_check ? "media_provider_live_probe" : "model_connection_check",
      probe_path: payload.probe_path ?? "/models",
      requested_live_check: Boolean(payload.live_check),
      route_reason: "prototype mode validates policy and routing shape without calling external providers",
    },
    latency_ms: 72,
    message: "Prototype connection accepted.",
    model_key: payload.model_key ?? null,
    ok: true,
    provider_key: providerKey,
  };
}

export function createPrototypeAcceptanceTest(deploymentId: string): LLMDeploymentAcceptanceTestResponse {
  const deployment =
    PROTOTYPE_MODEL_DEPLOYMENTS.find((item) => item.id === deploymentId) ?? PROTOTYPE_MODEL_DEPLOYMENTS[0];
  return {
    audit_action: "llm.deployment.acceptance_test",
    content_preview: "AgentHive prototype acceptance check ok.",
    deployment_id: deployment.id,
    evidence: {
      credential_configured: true,
      fallback_attempt_count: 0,
      selected_route_reason: "prototype",
    },
    live_network_call: false,
    mock: true,
    model_key: deployment.model_key,
    ok: true,
    provider_key: deployment.provider_key,
    request_id: `prototype-${Date.now()}`,
    route_attempts: [
      {
        attempt: 1,
        deployment_id: deployment.id,
        model_key: deployment.model_key,
        provider_key: deployment.provider_key,
        routing_key: deployment.routing_key,
        status: "success",
      },
    ],
    routing_key: deployment.routing_key,
    usage: {
      cost_usd: "0",
      input_tokens: 8,
      output_tokens: 6,
      total_tokens: 14,
    },
    usage_recorded: true,
  };
}

export function createPrototypeReadiness(): LLMReadinessResponse {
  const deployments = PROTOTYPE_MODEL_DEPLOYMENTS.map((deployment) => {
    const credentialConfigured =
      PROTOTYPE_MODEL_PROVIDERS.find((provider) => provider.provider_key === deployment.provider_key)
        ?.credential_configured ?? false;
    const blockers = credentialConfigured && deployment.status === "active" ? [] : ["credential_or_deployment_missing"];
    const warnings = deployment.config.fallback || deployment.config.fallback_group ? [] : ["fallback_not_configured"];
    const readiness = blockers.length ? "blocked" : warnings.length ? "warning" : "ready";
    return {
      blockers,
      credential_configured: credentialConfigured,
      deployment_active: deployment.status === "active",
      deployment_id: deployment.id,
      deployment_name: deployment.deployment_name,
      display_name: deployment.display_name,
      evidence: {
        mode: "prototype",
      },
      fallback_configured: warnings.length === 0,
      last_probe_message: "Prototype readiness evidence.",
      live_probe_checked_at: PROTOTYPE_NOW,
      live_probe_ok: readiness !== "blocked",
      model_key: deployment.model_key,
      policy_referenced: true,
      pricing_configured: true,
      provider_key: deployment.provider_key,
      provider_name: deployment.provider_name,
      readiness,
      routing_key: deployment.routing_key,
      warnings,
    };
  });
  return {
    deployments,
    generated_at: new Date().toISOString(),
    summary: {
      blocked: deployments.filter((item) => item.readiness === "blocked").length,
      ready: deployments.filter((item) => item.readiness === "ready").length,
      total: deployments.length,
      warning: deployments.filter((item) => item.readiness === "warning").length,
    },
  };
}

export function createPrototypePolicy(payload: LLMPolicyUpsertRequest): LLMPolicyResponse {
  return {
    allowed_models: payload.allowed_models,
    allowed_routing_keys: payload.allowed_routing_keys,
    created_at: PROTOTYPE_NOW,
    default_model_key: payload.default_model_key ?? null,
    default_routing_key: payload.default_routing_key ?? null,
    description: payload.description ?? null,
    effect: payload.effect,
    id: payload.id ?? "00000000-0000-4000-8000-000000119999",
    max_tokens: payload.max_tokens ?? null,
    metadata: payload.metadata ?? { mode: "prototype" },
    name: payload.name,
    priority: payload.priority,
    scope_id: payload.scope_id ?? null,
    scope_type: payload.scope_type,
    status: payload.status,
    tenant_id: PROTOTYPE_TENANT_ID,
    updated_at: new Date().toISOString(),
  };
}

export function updatePrototypePolicyStatus(policyId: string, status: LLMPolicyStatus): LLMPolicyResponse {
  const existing = PROTOTYPE_MODEL_POLICIES.find((policy) => policy.id === policyId) ?? PROTOTYPE_MODEL_POLICIES[0];
  return { ...existing, status, updated_at: new Date().toISOString() };
}

export function createPrototypePrice(payload: LLMModelPriceUpsertRequest): LLMModelPriceResponse {
  return {
    currency: payload.currency ?? "USD",
    display_name: payload.display_name ?? payload.model_key,
    effective_from: payload.effective_from ?? new Date().toISOString(),
    effective_to: payload.effective_to ?? null,
    id: "00000000-0000-4000-8000-000000129999",
    input_per_1k_tokens: payload.input_per_1k_tokens,
    model_id:
      PROTOTYPE_MODEL_DEPLOYMENTS.find(
        (deployment) => deployment.provider_key === payload.provider_key && deployment.model_key === payload.model_key,
      )?.id ?? "00000000-0000-4000-8000-000000109999",
    model_key: payload.model_key,
    output_per_1k_tokens: payload.output_per_1k_tokens,
    provider_key: payload.provider_key,
  };
}
